//! # D-Bus interface proxy for: `org.mpris.MediaPlayer2.Playlists`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
//! Source: `org.mpris.MediaPlayer2.Playlists.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(interface = "org.mpris.MediaPlayer2.Playlists", assume_defaults = true)]
pub trait Playlists {
    /// ActivatePlaylist method
    fn activate_playlist(&self, PlaylistId: &zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

    /// GetPlaylistIconFd method
    fn get_playlist_icon_fd(
        &self,
        PlaylistId: &zbus::zvariant::ObjectPath<'_>,
    ) -> zbus::Result<(String, zbus::zvariant::OwnedFd)>;

    /// GetPlaylists method
    fn get_playlists(
        &self,
        Index: u32,
        MaxCount: u32,
        Order: &str,
        ReverseOrder: bool,
    ) -> zbus::Result<Vec<(zbus::zvariant::OwnedObjectPath, String, String)>>;

    /// PlaylistChanged signal
    #[zbus(signal)]
    fn playlist_changed(
        &self,
        Playlist: (zbus::zvariant::ObjectPath<'_>, &str, &str),
    ) -> zbus::Result<()>;

    /// ActivePlaylist property
    #[zbus(property)]
    fn active_playlist(
        &self,
    ) -> zbus::Result<(bool, (zbus::zvariant::OwnedObjectPath, String, String))>;

    /// Orderings property
    #[zbus(property)]
    fn orderings(&self) -> zbus::Result<Vec<String>>;

    /// PlaylistCount property
    #[zbus(property)]
    fn playlist_count(&self) -> zbus::Result<u32>;
}
